# Generated by Django 3.2.15 on 2022-12-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, unique=True, verbose_name='адрес')),
                ('lat', models.FloatField(null=True, verbose_name='широта')),
                ('lon', models.FloatField(null=True, verbose_name='долгота')),
                ('updated_at', models.DateTimeField(verbose_name='дата обновления адреса')),
            ],
            options={
                'verbose_name': 'адрес',
                'verbose_name_plural': 'адреса',
            },
        ),
    ]
