# Generated by Django 3.2.15 on 2022-12-06 13:50

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='79000000000', max_length=128, region='RU', verbose_name='контактный номер'),
            preserve_default=False,
        ),
    ]
