# Generated by Django 3.2.15 on 2022-12-08 11:00

from django.db import migrations


def set_price_to_products_of_order(apps, schema_editor):
    OrderProduct = apps.get_model('foodcartapp', 'OrderProduct')
    Product = apps.get_model('foodcartapp', 'Product')

    products = Product.objects.all()
    for product in products:
        OrderProduct.objects.filter(product=product).update(price=product.price)


class Migration(migrations.Migration):
    dependencies = [
        ('foodcartapp', '0040_orderproduct_price'),
    ]

    operations = [
        migrations.RunPython(set_price_to_products_of_order),
    ]
