# Generated by Django 3.2.15 on 2022-12-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_alter_orderproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('WAITING', 'Ожидает'), ('PREPARING', 'Приготовливается'), ('READY', 'Готов'), ('DELIVERING', 'Доставляется'), ('COMPLETED', 'Выполнен')], default='CREATED', max_length=50, verbose_name='статус'),
        ),
    ]
