# Generated by Django 3.2.15 on 2022-12-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('WAITING', 'Ожидает'), ('PREPARING', 'Приготовливается'), ('READY', 'Готов'), ('DELIVERING', 'Доставляется'), ('COMPLETED', 'Выполнен')], db_index=True, default='CREATED', max_length=50, verbose_name='статус'),
        ),
    ]
