# Generated by Django 3.2.15 on 2022-12-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20221208_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('NOT_CHOSEN', 'Не выбран'), ('CASH', 'Налично'), ('CREDIT_CARD', 'Картой')], default='NOT_CHOSEN', max_length=50, verbose_name='способ оплаты'),
        ),
    ]
