# Generated by Django 3.2.15 on 2022-12-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_responsible_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('P10_NOT_CHOSEN', 'Не выбран'), ('P20_CASH', 'Налично'), ('P30_CREDIT_CARD', 'Картой')], default='P10_NOT_CHOSEN', max_length=50, verbose_name='способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('S10_CREATED', 'Создан'), ('S20_WAITING', 'Ожидает'), ('S30_PREPARING', 'Приготовливается'), ('S40_READY', 'Готов'), ('S50_DELIVERING', 'Доставляется'), ('S60_COMPLETED', 'Выполнен')], db_index=True, default='S10_CREATED', max_length=50, verbose_name='статус'),
        ),
    ]
