# Generated by Django 3.2.15 on 2022-12-09 15:51

from django.db import migrations


def change_status_choices(apps, schema_editor):
    Order = apps.get_model('foodcartapp', 'Order')
    Order.objects.filter(status='CREATED').update(status='S10_CREATED')
    Order.objects.filter(status='WAITING').update(status='S20_WAITING')
    Order.objects.filter(status='PREPARING').update(status='S30_PREPARING')
    Order.objects.filter(status='READY').update(status='S40_READY')
    Order.objects.filter(status='DELIVERING').update(status='S50_DELIVERING')
    Order.objects.filter(status='COMPLETED').update(status='S60_COMPLETED')


def change_status_choices_back(apps, schema_editor):
    Order = apps.get_model('foodcartapp', 'Order')
    Order.objects.filter(status='S10_CREATED').update(status='CREATED')
    Order.objects.filter(status='S20_CREATED').update(status='WAITING')
    Order.objects.filter(status='S30_CREATED').update(status='PREPARING')
    Order.objects.filter(status='S40_CREATED').update(status='READY')
    Order.objects.filter(status='S50_CREATED').update(status='DELIVERING')
    Order.objects.filter(status='S60_CREATED').update(status='COMPLETED')


def change_payment_type_choices(apps, schema_editor):
    Order = apps.get_model('foodcartapp', 'Order')
    Order.objects.filter(payment_type='NOT_CHOSEN').update(payment_type='P10_NOT_CHOSEN')
    Order.objects.filter(payment_type='CASH').update(payment_type='P20_CASH')
    Order.objects.filter(payment_type='CREDIT_CARD').update(payment_type='P30_CREDIT_CARD')


def change_payment_type_choices_back(apps, schema_editor):
    Order = apps.get_model('foodcartapp', 'Order')
    Order.objects.filter(payment_type='P10_NOT_CHOSEN').update(payment_type='NOT_CHOSEN')
    Order.objects.filter(payment_type='P20_CASH').update(payment_type='CASH')
    Order.objects.filter(payment_type='P30_CREDIT_CARD').update(payment_type='CREDIT_CARD')


class Migration(migrations.Migration):
    dependencies = [
        ('foodcartapp', '0048_auto_20221209_1849'),
    ]

    operations = [
        migrations.RunPython(code=change_status_choices, reverse_code=change_status_choices_back),
        migrations.RunPython(code=change_payment_type_choices, reverse_code=change_payment_type_choices_back)
    ]
